services:
  - type: web
    name: my-app-name # the name of this service, you should change this
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "bin/render-build.sh" # we already created this file for you
    startCommand: "bin/server"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
databases: # this section provides some additional database configuration
  - name: db
    plan: free
    ipAllowList: []
